UNIQUE_ID_ERROR = 'дистрибьютор с таким внешним ID уже существует в базе под именем:'